export const CREATE_MAIN_SOCKET = "CREATE_MAIN_SOCKET";
export const CREATE_UPDATE_SOCKET = "CREATE_UPDATE_SOCKET";
export const PING = "PING";
export const SET_ALIVE_STATE = "SET_ALIVE_STATE";

export const CONNECT_WEBSOCKET = "CONNECT_WEBSOCKET";
export const CLOSE_WEBSOCKET = "CLOSE_WEBSOCKET";

export const CONNECT_UPDATESOCKET = "CONNECT_UPDATESOCKET";
export const UPDATE_CONNECTION_LOADING = "UPDATE_CONNECTION_LOADING";
export const UPDATE_CONNECTION_SUCCESSFUL = "UPDATE_CONNECTION_SUCCESSFUL";
export const UPDATE_CONNECTION_FAILED = "UPDATE_CONNECTION_FAILED";

export const CLOSE_EXISTING_CONNECTION = "CLOSE_EXISTING_CONNECTION";

export const CONNECTION_LOADING = "CONNECTION_LOADING";
export const CONNECTION_SUCCESSFUL = "CONNECTION_SUCCESSFUL";
export const CONNECTION_FAILED = "CONNECTION_FAILED";
export const CONNECTION_LOST = "CONNECTION_LOST";
export const CONNECTION_CLOSED = "CONNECTION_CLOSED";
export const WAITING_CONNECTION = "WAITING_CONNECTION";

export const STREAMS_LOADING = "STREAMS_LOADING";
export const STREAMS_CONNECTION_SUCCESSFUL = "STREAMS_CONNECTION_SUCCESSFUL";
export const STREAMS_CONNECTION_FAILED = "STREAMS_CONNECTION_FAILED";

export const REFRESH_TARGETS = "REFRESH_TARGETS";
export const REFRESH_CAMERA = "REFRESH_CAMERA";
export const REFRESH_DISTANCE_LINES = "REFRESH_DISTANCE_LINES";
export const REFRESH_ALARM_STATE = "REFRESH_ALARM_STATE";
export const REFRESH_SETTINGS = "REFRESH_SETTINGS";
export const REFRESH_VERSIONS = "REFRESH_VERSIONS";
export const REFRESH_SETTING = "REFRESH_SETTING";
export const REFRESH_STATE = "REFRESH_STATE";
export const REFRESH_BOATBUS = "REFRESH_BOATBUS";
export const REFRESH_ERROR = "REFRESH_ERROR";

export const REFRESH_UPDATE = "REFRESH_UPDATE";
export const REMOVE_UPDATE_ERROR = "REMOVE_UPDATE_ERROR";

export const LISTEN_OBSTACLES = "LISTEN_OBSTACLES";
export const LISTEN_PTU = "LISTEN_PTU";

export const ACTIVATE_BIG_THERMAL_STREAM = "ACTIVATE_BIG_TERMAL_STREAM";
export const ACTIVATE_BIG_COLOR_STREAM = "ACTIVATE_BIG_COLOR_STREAM";
export const ACTIVATE_BIG_MAP = "ACTIVATE_BIG_MAP";
export const ACTIVATE_SMALL_THERMAL_STREAM = "ACTIVATE_SMALL_TERMAL_STREAM";
export const ACTIVATE_SMALL_COLOR_STREAM = "ACTIVATE_SMALL_COLOR_STREAM";
export const ACTIVATE_SMALL_MAP = "ACTIVATE_SMALL_MAP";
export const SET_BIG_STREAM_ZOOM = "SET_BIG_STREAM_ZOOM";
export const SET_BIG_MAP_ZOOM = "SET_BIG_MAP_ZOOM";
export const SET_SMALL_STREAM_ZOOM = "SET_SMALL_STREAM_ZOOM";
export const SET_SMALL_MAP_ZOOM = "SET_SMALL_MAP_ZOOM";

export const SET_VIEW = "SET_VIEW";

export const GET_SETTINGS = "GET_SETTINGS";
export const GET_VERSIONS = "GET_VERSIONS";
export const GET_STATE = "GET_STATE";

export const START_SUBSCRIPTIONS = "START_SUBSCRIPTIONS";
export const SUBSCRIBE_STATUS = "SUBSCRIBE_STATUS";
export const SUBSCRIBE_STREAMS = "SUBSCRIBE_STREAMS";
export const SUBSCRIBE_STATE = "SUBSCRIBE_STATE";
export const SUBSCRIBE_BOATBUS = "SUBSCRIBE_BOATBUS";
export const SUBSCRIBE_ERROR = "SUBSCRIBE_ERROR";

export const SWITCH_ALARM_MODE = "SWITCH_ALARM_MODE";
export const SET_TARGET_LIST = "SET_TARGET_LIST";
export const ACTIVATE_TARGET_LIST = "ACTIVATE_TARGET_LIST";
export const DEACTIVATE_TARGET_LIST = "DEACTIVATE_TARGET_LIST";
export const ACTIVATE_SETTINGS = "ACTIVATE_SETTINGS";
export const DEACTIVATE_SETTINGS = "DEACTIVATE_SETTINGS";
export const ACTIVATE_CONTROLS = "ACTIVATE_CONTROLS";
export const DEACTIVATE_CONTROLS = "DEACTIVATE_CONTROLS";

export const SET_CONFIG_SETTING = "SET_CONFIG_SETTING";
export const SET_CACHE_SETTING = "SET_CACHE_SETTING";

export const REQUEST_FAILED = "REQUEST_FAILED";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_LOADING = "REQUEST_LOADING";
export const ACKNOWLEDGE_REQUEST_FAILURE = "ACKNOWLEDGE_REQUEST_FAILURE";

export const LOAD_CACHE = "LOAD_CACHE";

export const SET_IP = "SET_IP";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_THEME = "SET_THEME";
export const SET_HIDE_BOATBUS = "SET_HIDE_BOATBUS";
export const SET_DEVELOPER_MODE = "SET_DEVELOPER_MODE";
export const SET_INSTALLER_MODE = "SET_INSTALLER_MODE";
export const SET_SETTINGS_LABEL = "SET_SETTINGS_LABEL";
export const SET_DISTANCE_METRIC = "SET_DISTANCE_METRIC";
export const SET_SPEED_METRIC = "SET_SPEED_METRIC";
export const SET_TEMPERATURE_METRIC = "SET_TEMPERATURE_METRIC";
export const SET_ANGLE_METRIC = "SET_ANGLE_METRIC";

export const TILT_CAMERA = "TILT_CAMERA";
export const PAN_CAMERA = "PAN_CAMERA";
export const DRAG_AND_DROP = "DRAG_AND_DROP";

export const ADD_SELECTED_TARGET = "ADD_SELECTED_TARGET";

export const START_UPDATE = "START_UPDATE";
export const FINISH_UPDATE = "FINISH_UPDATE";

export const START_MASK_ROUTINE = "START_MASK_ROUTINE";
export const STOP_MASK_ROUTINE = "STOP_MASK_ROUTINE";
export const UPLOAD_MASK = "UPLOAD_MASK";
export const MASK_SUBMITTED = "MASK_SUBMITTED";

export const SET_TARGET_LIST_IMAGE = "SET_TARGET_LIST_IMAGE";
export const SUBSCRIBE_SYNC_SETTING = "SUBSCRIBE_SYNC_SETTING";

export const SET_NMEA_GATEWAY = "SET_NMEA_GATEWAY";

export const START_PANORAMA_RECORDING = "START_PANORAMA_RECORDING";
export const STOP_PANORAMA_RECORDING = "STOP_PANORAMA_RECORDING";
export const START_STREAM_RECORDING = "START_STREAM_RECORDING";
export const STOP_STREAM_RECORDING = "STOP_STREAM_RECORDING";
export const START_SNAPSHOT_RECORDING = "START_SNAPSHOT_RECORDING";
export const STOP_SNAPSHOT_RECORDING = "STOP_SNAPSHOT_RECORDING";
export const START_IMU_RECORDING = "START_IMU_RECORDING";
export const STOP_IMU_RECORDING = "STOP_IMU_RECORDING";
export const FINISHED_PANORAMA_RECORDING = "FINISHED_PANORAMA_RECORDING";
